### ISSUE TITLE
Please provide more services

### ISSUE THREAD

**Issue by piejanssens** [leonardehrenfried/html5ify#1]
Check out this website
Make your extension compatible with the JS from here: http://hoyois.github.com/safariextensions/clicktoplugin/killers.xhtml

**Comment by leonardehrenfried** [comment]
Hi Pieter,

thanks for the suggestion!

Sadly, I don't really see myself ever finding the time and motivation to
implement this. I will keep the issue open as a reminder for myself should
I ever struggle to have something to do.

All the best,
Leonard
